example1/config/routes.rb
Rails.application.routes.draw do
  get 'top/index'

  root :to => 'top#index' 

  resources :users
  resources :depts

end

example1/app/models/dept.rb
class Dept < ActiveRecord::Base
  has_many :users, dependent: :destroy
end

example1/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :dept
end

example1/app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  before_action :set_dept, only: [:show, :edit, :update, :destroy]

  # GET /depts
  # GET /depts.json
  def index
    @depts = Dept.all
  end

  # GET /depts/1
  # GET /depts/1.json
  def show
  end

  # GET /depts/new
  def new
    @dept = Dept.new
  end

  # GET /depts/1/edit
  def edit
  end

  # POST /depts
  # POST /depts.json
  def create
    @dept = Dept.new(dept_params)

    respond_to do |format|
      if @dept.save
        format.html { redirect_to @dept, notice: 'Dept was successfully created.' }
        format.json { render :show, status: :created, location: @dept }
      else
        format.html { render :new }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /depts/1
  # PATCH/PUT /depts/1.json
  def update
    respond_to do |format|
      if @dept.update(dept_params)
        format.html { redirect_to @dept, notice: 'Dept was successfully updated.' }
        format.json { render :show, status: :ok, location: @dept }
      else
        format.html { render :edit }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depts/1
  # DELETE /depts/1.json
  def destroy
    @dept.destroy
    respond_to do |format|
      format.html { redirect_to depts_url, notice: 'Dept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dept
      @dept = Dept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dept_params
      params.require(:dept).permit(:name)
    end
end

example1/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

example1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @dept = Dept.all
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :dept_id)
    end
end

example1/app/helpers/depts_helper.rb
module DeptsHelper
end

example1/app/helpers/top_helper.rb
module TopHelper
end

example1/app/helpers/users_helper.rb
module UsersHelper
end

example1/app/views/depts/_form.html.erb
<%= form_for(@dept) do |f| %>
  <% if @dept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dept.errors.count, "error") %> prohibited this dept from being saved:</h2>

      <ul>
      <% @dept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

example1/app/views/depts/edit.html.erb
<h1>Editing Dept</h1>

<%= render 'form' %>

<%= link_to 'Show', @dept %> |
<%= link_to 'Back', depts_path %>

example1/app/views/depts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Depts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @depts.each do |dept| %>
      <tr>
        <td><%= dept.name %></td>
        <td><%= link_to 'Show', dept %></td>
        <td><%= link_to 'Edit', edit_dept_path(dept) %></td>
        <td><%= link_to 'Destroy', dept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <% dept.users.each do |user| %>
            <span><%= user.name %></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dept', new_dept_path %>
<%= link_to 'Top', top_index_path %>

example1/app/views/depts/new.html.erb
<h1>New Dept</h1>

<%= render 'form' %>

<%= link_to 'Back', depts_path %>

example1/app/views/depts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dept.name %>
</p>

<%= link_to 'Edit', edit_dept_path(@dept) %> |
<%= link_to 'Back', depts_path %>

example1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

example1/app/views/top/index.html.erb
<h1>Top</h1>

<%= link_to 'Depts', depts_path %>
<%= link_to 'Users', users_path %>

example1/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.collection_select(:dept_id, @dept, :id, :name) %>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

example1/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

example1/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dept</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.dept.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Top', top_index_path %>

example1/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

example1/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @user.dept %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>